# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Drive\PythonProject\NCKH-Project\design\WidgetViewCamera.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import CameraViewfiderCreator
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1308, 857)
        self.camera1 = QtWidgets.QWidget(Form)
        self.camera1.setGeometry(QtCore.QRect(26, 40, 411, 281))
        self.camera1.setObjectName("camera1")
        self.widget_4 = QtWidgets.QWidget(self.camera1)
        self.widget_4.setGeometry(QtCore.QRect(0, 0, 411, 281))
        self.widget_4.setObjectName("widget_4")
        self.camera3 = QtWidgets.QWidget(Form)
        self.camera3.setGeometry(QtCore.QRect(866, 40, 411, 281))
        self.camera3.setObjectName("camera3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.camera3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 411, 281))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.camera5 = QtWidgets.QWidget(Form)
        self.camera5.setGeometry(QtCore.QRect(446, 330, 411, 281))
        self.camera5.setObjectName("camera5")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.camera5)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 411, 281))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.saveImageButton = QtWidgets.QPushButton(Form)
        self.saveImageButton.setGeometry(QtCore.QRect(806, 750, 75, 23))
        self.saveImageButton.setObjectName("saveImageButton")
        self.timeLineLabel = QtWidgets.QLabel(Form)
        self.timeLineLabel.setGeometry(QtCore.QRect(202, 660, 61, 21))
        self.timeLineLabel.setTextFormat(QtCore.Qt.RichText)
        self.timeLineLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLineLabel.setObjectName("timeLineLabel")
        self.captureImageButton = QtWidgets.QPushButton(Form)
        self.captureImageButton.setGeometry(QtCore.QRect(640, 750, 101, 23))
        self.captureImageButton.setObjectName("captureImageButton")
        self.capturedImage = QtWidgets.QWidget(Form)
        self.capturedImage.setGeometry(QtCore.QRect(1016, 660, 231, 161))
        self.capturedImage.setObjectName("capturedImage")
        self.camera6 = QtWidgets.QWidget(Form)
        self.camera6.setGeometry(QtCore.QRect(866, 330, 411, 281))
        self.camera6.setObjectName("camera6")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.camera6)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 411, 281))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_6)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.timeLineSlider = QtWidgets.QSlider(Form)
        self.timeLineSlider.setGeometry(QtCore.QRect(26, 630, 1251, 22))
        self.timeLineSlider.setProperty("value", 99)
        self.timeLineSlider.setTracking(True)
        self.timeLineSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeLineSlider.setInvertedAppearance(False)
        self.timeLineSlider.setInvertedControls(False)
        self.timeLineSlider.setTickInterval(6)
        self.timeLineSlider.setObjectName("timeLineSlider")
        self.camera2 = QtWidgets.QWidget(Form)
        self.camera2.setGeometry(QtCore.QRect(446, 40, 411, 281))
        self.camera2.setObjectName("camera2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.camera2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 411, 281))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.camera4 = QtWidgets.QWidget(Form)
        self.camera4.setGeometry(QtCore.QRect(26, 330, 411, 281))
        self.camera4.setObjectName("camera4")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.camera4)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 411, 281))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pauseButton = QtWidgets.QPushButton(Form)
        self.pauseButton.setGeometry(QtCore.QRect(546, 660, 75, 23))
        self.pauseButton.setObjectName("pauseButton")
        self.playButton = QtWidgets.QPushButton(Form)
        self.playButton.setGeometry(QtCore.QRect(656, 660, 75, 23))
        self.playButton.setObjectName("playButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.saveImageButton.setText(_translate("Form", "Save Image"))
        self.timeLineLabel.setText(_translate("Form", "23:34:55"))
        self.captureImageButton.setText(_translate("Form", "Capture Image"))
        self.pauseButton.setText(_translate("Form", "Pause"))
        self.playButton.setText(_translate("Form", "Play"))



app = QtWidgets.QApplication([])

mainWindow = QtWidgets.QMainWindow()
mainWindow.setWindowTitle("this is window")

widget = QtWidgets.QWidget()
view = Ui_Form()
view.setupUi(widget)

creator = CameraViewfiderCreator.CameraViewfiderFactory()
camerainfo = creator.availableCameras()[0]
camera = creator.createCameraObject(camerainfo)
viewfinder = creator.createCameraViewfider(camera)
viewfinder.setVisible(True)

print(3)
view.camera1.layout().addWidget(viewfinder)
print(viewfinder)
mainWindow.resize(1308, 857)
mainWindow.setCentralWidget(widget)
mainWindow.setVisible(True)
mainWindow.show()
# mainWindow.show()

app.exec_()