# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Drive\PythonProject\NCKH-Project\design\AddRemoteCameraDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AddRemoteCameraDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 332)
        self.toolBox = QtWidgets.QToolBox(Dialog)
        self.toolBox.setGeometry(QtCore.QRect(0, 0, 401, 331))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 401, 277))
        self.page.setObjectName("page")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 101, 16))
        self.label_3.setObjectName("label_3")
        self.cancelPushButton = QtWidgets.QPushButton(self.page)
        self.cancelPushButton.setGeometry(QtCore.QRect(260, 230, 75, 23))
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 91, 16))
        self.label_2.setObjectName("label_2")
        self.passwordLineEdit = QtWidgets.QLineEdit(self.page)
        self.passwordLineEdit.setGeometry(QtCore.QRect(160, 120, 181, 20))
        self.passwordLineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(30, 0, 91, 16))
        self.label_4.setObjectName("label_4")
        self.usernameLineEdit = QtWidgets.QLineEdit(self.page)
        self.usernameLineEdit.setGeometry(QtCore.QRect(160, 80, 181, 20))
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.page)
        self.plainTextEdit.setEnabled(True)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 160, 341, 41))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.urlLineEdit = QtWidgets.QLineEdit(self.page)
        self.urlLineEdit.setGeometry(QtCore.QRect(160, 40, 181, 20))
        self.urlLineEdit.setObjectName("urlLineEdit")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(30, 40, 91, 16))
        self.label.setObjectName("label")
        self.nameCameraLineEdit = QtWidgets.QLineEdit(self.page)
        self.nameCameraLineEdit.setGeometry(QtCore.QRect(160, 0, 181, 20))
        self.nameCameraLineEdit.setObjectName("nameCameraLineEdit")
        self.okayPushButton = QtWidgets.QPushButton(self.page)
        self.okayPushButton.setGeometry(QtCore.QRect(160, 230, 75, 23))
        self.okayPushButton.setObjectName("okayPushButton")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 401, 277))
        self.page_2.setObjectName("page_2")
        self.cameraListComboBox = QtWidgets.QComboBox(self.page_2)
        self.cameraListComboBox.setGeometry(QtCore.QRect(200, 90, 111, 22))
        self.cameraListComboBox.setObjectName("cameraListComboBox")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(60, 90, 111, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setGeometry(QtCore.QRect(60, 60, 111, 21))
        self.label_6.setObjectName("label_6")
        self.nameCameraLineEdit_2 = QtWidgets.QLineEdit(self.page_2)
        self.nameCameraLineEdit_2.setGeometry(QtCore.QRect(200, 60, 113, 20))
        self.nameCameraLineEdit_2.setObjectName("nameCameraLineEdit_2")
        self.okayPushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.okayPushButton_2.setGeometry(QtCore.QRect(160, 160, 75, 23))
        self.okayPushButton_2.setObjectName("okayPushButton_2")
        self.cancelPushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.cancelPushButton_2.setGeometry(QtCore.QRect(260, 160, 75, 23))
        self.cancelPushButton_2.setObjectName("cancelPushButton_2")
        self.toolBox.addItem(self.page_2, "")

        self.retranslateUi(Dialog)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Password:"))
        self.cancelPushButton.setText(_translate("Dialog", "Cancel"))
        self.label_2.setText(_translate("Dialog", "User name: "))
        self.label_4.setText(_translate("Dialog", "Camera name:"))
        self.plainTextEdit.setPlainText(_translate("Dialog", "Đường dẫn sử dụng giao thức RTSP \n"
"vd: \"rtsp://192.168.1.210:554/Streaming/Channels/101\""))
        self.label.setText(_translate("Dialog", "Link:"))
        self.okayPushButton.setText(_translate("Dialog", "Add"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Dialog", "Remote Camera"))
        self.label_5.setText(_translate("Dialog", "Availabel cameras : "))
        self.label_6.setText(_translate("Dialog", "Camera name:"))
        self.okayPushButton_2.setText(_translate("Dialog", "Add"))
        self.cancelPushButton_2.setText(_translate("Dialog", "Cancel"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Dialog", "Local Camera"))
