# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Drive\PythonProject\NCKH-Project\design\AlertDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AlertDialog(object):
    def __init__(self) -> None:
        super().__init__()
        self.dialog = QtWidgets.QDialog()
        self.setupUi(self.dialog)
        self.dialog.setModal(True)
    
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 139)
        self.okayPushButton = QtWidgets.QPushButton(Dialog)
        self.okayPushButton.setGeometry(QtCore.QRect(160, 90, 75, 23))
        self.okayPushButton.setFlat(False)
        self.okayPushButton.setObjectName("okayPushButton")
        self.okayPushButton.clicked.connect(self.setInVisible)
        self.alertTextLabel = QtWidgets.QLabel(Dialog)
        self.alertTextLabel.setGeometry(QtCore.QRect(10, 30, 371, 41))
        self.alertTextLabel.setText("")
        self.alertTextLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.alertTextLabel.setObjectName("alertTextLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.okayPushButton.setText(_translate("Dialog", "Okay"))
        
    def tenCameraKhongHopLe(self):
        self.alertTextLabel.setText("Tên camera không hợp lệ")
        self.dialog.setVisible(True)
        
    def tenFileHoacĐuongDanKhongHopLe(self):
        self.alertTextLabel.setText("Tên file hoặc đường dẫn không hợp lệ")
        self.dialog.setVisible(True)
        
    def vuiLongKetNoiLaiCamera(self):
        self.alertTextLabel.setText("Vui lòng kết nối lại camera")
        self.dialog.setVisible(True)
    
    def setInVisible(self):
        self.dialog.setVisible(False)
        
