# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Drive\PythonProject\NCKH-Project\design\DockWidgetViewCamera.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(1302, 874)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.camera5 = QtWidgets.QWidget(self.dockWidgetContents)
        self.camera5.setGeometry(QtCore.QRect(440, 320, 411, 281))
        self.camera5.setObjectName("camera5")
        self.camera1 = QtWidgets.QWidget(self.dockWidgetContents)
        self.camera1.setGeometry(QtCore.QRect(20, 30, 411, 281))
        self.camera1.setObjectName("camera1")
        self.widget_4 = QtWidgets.QWidget(self.camera1)
        self.widget_4.setGeometry(QtCore.QRect(0, 0, 411, 281))
        self.widget_4.setObjectName("widget_4")
        self.timeLineLabel = QtWidgets.QLabel(self.dockWidgetContents)
        self.timeLineLabel.setGeometry(QtCore.QRect(196, 650, 61, 21))
        self.timeLineLabel.setTextFormat(QtCore.Qt.RichText)
        self.timeLineLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLineLabel.setObjectName("timeLineLabel")
        self.capturedImage = QtWidgets.QWidget(self.dockWidgetContents)
        self.capturedImage.setGeometry(QtCore.QRect(1010, 650, 231, 161))
        self.capturedImage.setObjectName("capturedImage")
        self.timeLineSlider = QtWidgets.QSlider(self.dockWidgetContents)
        self.timeLineSlider.setGeometry(QtCore.QRect(20, 620, 1251, 22))
        self.timeLineSlider.setProperty("value", 99)
        self.timeLineSlider.setTracking(True)
        self.timeLineSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeLineSlider.setInvertedAppearance(False)
        self.timeLineSlider.setInvertedControls(False)
        self.timeLineSlider.setTickInterval(6)
        self.timeLineSlider.setObjectName("timeLineSlider")
        self.camera4 = QtWidgets.QWidget(self.dockWidgetContents)
        self.camera4.setGeometry(QtCore.QRect(20, 320, 411, 281))
        self.camera4.setObjectName("camera4")
        self.camera2 = QtWidgets.QWidget(self.dockWidgetContents)
        self.camera2.setGeometry(QtCore.QRect(440, 30, 411, 281))
        self.camera2.setObjectName("camera2")
        self.pauseButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pauseButton.setGeometry(QtCore.QRect(540, 650, 75, 23))
        self.pauseButton.setObjectName("pauseButton")
        self.playButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.playButton.setGeometry(QtCore.QRect(650, 650, 75, 23))
        self.playButton.setObjectName("playButton")
        self.camera6 = QtWidgets.QWidget(self.dockWidgetContents)
        self.camera6.setGeometry(QtCore.QRect(860, 320, 411, 281))
        self.camera6.setObjectName("camera6")
        self.captureImageButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.captureImageButton.setGeometry(QtCore.QRect(634, 740, 101, 23))
        self.captureImageButton.setObjectName("captureImageButton")
        self.saveImageButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.saveImageButton.setGeometry(QtCore.QRect(800, 740, 75, 23))
        self.saveImageButton.setObjectName("saveImageButton")
        self.camera3 = QtWidgets.QWidget(self.dockWidgetContents)
        self.camera3.setGeometry(QtCore.QRect(860, 30, 411, 281))
        self.camera3.setObjectName("camera3")
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget"))
        self.timeLineLabel.setText(_translate("DockWidget", "23:34:55"))
        self.pauseButton.setText(_translate("DockWidget", "Pause"))
        self.playButton.setText(_translate("DockWidget", "Play"))
        self.captureImageButton.setText(_translate("DockWidget", "Capture Image"))
        self.saveImageButton.setText(_translate("DockWidget", "Save Image"))
